📌 What is an Execution Plan?

🧠 Definition
Execution Plan is a roadmap generated by SQL Server Query Optimizer that shows how a query will be executed 
to retrieve the required data with the lowest estimated cost.

-------------------------------------------------------------------------------------------------------
🏦 Insurance Example

Suppose Customer table मध्ये 20 लाख records आहेत.

तू query लिहितोस:

SELECT *
FROM Customer
WHERE CustomerID = 1001;

तू SQL लिहिलीस.

आता SQL Server विचार करतो...

"ही query execute करण्याचा सर्वात कमी cost चा मार्ग कोणता?"

तो Execution Plan तयार करतो.
-----------------------------------------------------------------------------------------------------
🧠 Real Meaning

Execution Plan सांगतो:

कोणता Index वापरला?
Table Scan झाला का?
Index Seek झाला का?
Join कोणता वापरला?
कोणत्या operator ला किती cost आहे?

==========================================================================
🔥 Operators you should know

Interviewers हे icons दाखवतात.

Operator						Meaning
Index Seek						Fast search
Index Scan						Reads many index entries
Table Scan						Reads whole table
Key Lookup						Fetches remaining columns from clustered index
Nested Loop Join				Best for small datasets
Hash Match						Best for large datasets
Sort							Sorting data
Filter							Applying WHERE condition






